name: Publish Docker image

on:
  release:
    types: [published]

jobs:

  build_and_pub:

    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: ./build.sh --trik-studio-version-kind master --docker-hub-user $USERNAME

      - name: Push tagged image to docker.io
        run: |
          CURRENT_NAME="$(docker images | tail -n +2 | awk '{print $1":"$2}' | head -n 1)"
          NEW_NAME="${CURRENT_NAME}-${GITHUB_REF:11}"
          docker tag "$CURRENT_NAME" "$NEW_NAME"
          docker push "$NEW_NAME"
